version: '3'
services:
  mosquitto:
    image: pascaldevink/rpi-mosquitto
    ports:
     - "9001:9001"
     - "1883:1883"
    deploy:
      restart_policy: 
          condition: on-failure 
  influxdb:
    image: hypriot/rpi-influxdb
    deploy:
      restart_policy: 
          condition: on-failure 
    environment:
     - INFLUXDB_INIT_PWD="password"
     - PRE_CREATE_DB="iot"
    ports:
     - "8083:8083"
     - "8086:8086"
    volumes:
     - influx-data:/data
  grafana:
    image: fg2it/grafana-armhf:v4.6.3
    deploy:
      restart_policy: 
        condition: on-failure 
    ports:
     - "3000:3000"
    volumes:
      - grafana-db:/var/lib/grafana
      - grafana-log:/var/log/grafana
      - grafana-conf:/etc/grafana
  openhab:
    image: "openhab/openhab:2.3.0-armhf-debian"
    deploy:
      restart_policy:
        condition: on-failure
    ports:
      - "8080:8080"
      - "8443:8443"
      - "8101:8101"
    volumes:
     - /etc/localtime:/etc/localtime:ro
     - /etc/timezone:/etc/timezone:ro
     - openhab-addons:/openhab/addons
     - openhab-conf:/openhab/conf
     - openhab-userdata:/openhab/userdata           
  pihole:
    restart: unless-stopped
    container_name: pihole
    image: pihole/pihole
    volumes:
      - /var/pihole:/etc/pihole
    environment:
      - ServerIP=192.168.1.6
    cap_add:
      - NET_ADMIN
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80"
volumes:
  influx-data:
    driver: local
  grafana-db:
    driver: local  
  grafana-log:
    driver: local
  grafana-conf:
    driver: local
  openhab-addons:
    driver: local
  openhab-conf:
    driver: local
  openhab-userdata:
    driver: local

