version: '3'
services:
  mosquitto:
    image: pascaldevink/rpi-mosquitto
    ports:
     - "9001:9001"
     - "1883:1883"
    deploy:
      restart_policy: 
          condition: on-failure 
  influxdb:
    image: influxdb:1.7.3
    container_name: influxdb
    deploy:
      restart_policy: 
          condition: on-failure 
    environment:
     - INFLUXDB_INIT_PWD="password"
     - PRE_CREATE_DB="iot"
    ports:
     - "8083:8083"
     - "8086:8086"
     - "8090:8090"
    env_file:
     - 'env.influxdb'
    volumes:
     - influx-data:/data
  grafana:
    image: grafana/grafana:5.4.3
    container_name: grafana
    ports:
     - "3000:3000"
    env_file:
     - 'env.grafana'
    links:
     - influxdb
    volumes:
      - grafana-db:/var/lib/grafana
      - grafana-log:/var/log/grafana
      - grafana-conf:/etc/grafana
  openhab:
    image: "openhab/openhab:2.3.0-armhf-debian"
    deploy:
      restart_policy:
        condition: on-failure
    ports:
      - "8080:8080"
      - "8443:8443"
      - "8101:8101"
    volumes:
     - /etc/localtime:/etc/localtime:ro
     - /etc/timezone:/etc/timezone:ro
     - openhab-addons:/openhab/addons
     - openhab-conf:/openhab/conf
     - openhab-userdata:/openhab/userdata           
  pihole:
    restart: unless-stopped
    container_name: pihole
    image: pihole/pihole:latest
    dns:
      - 127.0.0.1
      - 1.1.1.1
    volumes:
      - /var/pihole:/etc/pihole
    environment:
      ServerIP: 192.168.1.6
      PROXY_LOCATION: pihole
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
      - "443:443/tcp"
volumes:
  influx-data:
    driver: local
  grafana-db:
    driver: local  
  grafana-log:
    driver: local
  grafana-conf:
    driver: local
  openhab-addons:
    driver: local
  openhab-conf:
    driver: local
  openhab-userdata:
    driver: local

